# Generated by Django 2.1.4 on 2018-12-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageField',
            new_name='ImageModel',
        ),
    ]
