# Generated by Django 2.1.4 on 2018-12-19 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='seller',
        ),
        migrations.AddField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='properties'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='properties'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='properties'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='properties'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='properties'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='properties'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_main',
            field=models.ImageField(blank=True, default='', upload_to='properties'),
        ),
        migrations.AddField(
            model_name='property',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
