# Generated by Django 2.1.4 on 2018-12-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20181217_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_main',
        ),
    ]
