# Generated by Django 2.1.4 on 2018-12-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20181217_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='properties/%d'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.Property'),
        ),
    ]
